import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import type { GenreType } from "@/types/global";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Play, Clapperboard } from "lucide-react";
import { cn } from "@/lib/utils";
import { Input } from "@/components/ui/input";
import { redirect } from "next/navigation";

async function fetchGenres(): Promise<GenreType[]> {
    const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
        headers: {
           Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
        }
    })

    const data = await res.json();
    return data.genres;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const genres = await fetchGenres();

  async function search(formData: FormData) {
    "use server";
    redirect(`/search?q=${formData.get("q")}`);
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
          <header className="p-4 w-full bg-gray-300 border-b border-gray-400/60 flex justify-between gap-4 items-center">
              <div>
                <h1 className="text-3xl font-bold flex gap-4 items-center">
                  <Clapperboard size={28} />
                  Movie App
                </h1>
              </div>

              <div>
                <form className="flex gap-1" action={search}>
                  <Input placeholder="Search" name="q"/>
                  <Button type="submit">Search</Button>
                </form>
              </div>
          </header>

          <main className="flex">
              <aside className="w-50 min-h-150 bg-gray-300 p-4 flex flex-col gap-1">
                  <Button variant="default" className="font-bold" size="lg" asChild>
                      <Link href={`/`} className="flex gap-1 justify-start">
                        <Play />
                        All Genres
                      </Link>
                  </Button>
                  {genres.map(genre => {
                      return (
                        <Button 
                          asChild
                          size="lg"
                          key={genre.id}
                          variant="outline" 
                          className="cursor-pointer flex gap-1 justify-start"
                           >
                            <Link href={`/genre/${genre.name}/${genre.id}`}>
                              <Play />
                              {genre.name}
                            </Link>
                        </Button>
                      )
                  })}
              </aside>
              <section className="p-4">{children}</section>
          </main>
      </body>
    </html>
  );
}
