import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import type { GenreType } from "@/types/global";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Play, Clapperboard } from "lucide-react";
import { cn } from "@/lib/utils";
import { Input } from "@/components/ui/input";
import { redirect } from "next/navigation";

async function fetchGenres(): Promise<GenreType[]> {
    const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
        headers: {
           Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
        }
    })

    const data = await res.json();
    return data.genres;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const genres = await fetchGenres();

  async function search(formData: FormData) {
    "use server";
    redirect(`/search?q=${formData.get("q")}`);
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
          <section className="p-4">{children}</section>
      </body>
    </html>
  );
}
